# Generated by Django 6.0.2 on 2026-02-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_user_options_remove_user_role_alter_user_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
